
package custodiancxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.1
 * Thu Mar 17 22:00:19 CET 2022
 * Generated source version: 3.5.1
 */

@XmlRootElement(name = "RemoveStockResponse", namespace = "http://custodiancxf/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RemoveStockResponse", namespace = "http://custodiancxf/")

public class RemoveStockResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

