
package custodiancxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.1
 * Thu Mar 17 22:00:19 CET 2022
 * Generated source version: 3.5.1
 */

@XmlRootElement(name = "RemoveStock", namespace = "http://custodiancxf/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RemoveStock", namespace = "http://custodiancxf/")

public class RemoveStock {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

