package custodian;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-17T22:31:35.171+01:00
 * Generated source version: 3.5.1
 *
 */
@WebServiceClient(name = "CustodianImplService",
                  wsdlLocation = "http://localhost:8000/Custodian?WSDL",
                  targetNamespace = "http://custodian/")
public class CustodianImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://custodian/", "CustodianImplService");
    public final static QName CustodianImplPort = new QName("http://custodian/", "CustodianImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8000/Custodian?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustodianImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8000/Custodian?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public CustodianImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustodianImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustodianImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CustodianImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CustodianImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CustodianImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Custodian
     */
    @WebEndpoint(name = "CustodianImplPort")
    public Custodian getCustodianImplPort() {
        return super.getPort(CustodianImplPort, Custodian.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Custodian
     */
    @WebEndpoint(name = "CustodianImplPort")
    public Custodian getCustodianImplPort(WebServiceFeature... features) {
        return super.getPort(CustodianImplPort, Custodian.class, features);
    }

}
