
package custodian;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-17T22:31:35.111+01:00
 * Generated source version: 3.5.1
 *
 */
public final class Custodian_CustodianImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://custodian/", "CustodianImplService");

    private Custodian_CustodianImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CustodianImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        CustodianImplService ss = new CustodianImplService(wsdlURL, SERVICE_NAME);
        Custodian port = ss.getCustodianImplPort();

        {
        System.out.println("Invoking removeStock...");
        int _removeStock_arg0 = 42;
        java.lang.String _removeStock__return = port.removeStock(_removeStock_arg0);
        System.out.println("removeStock.result=" + _removeStock__return);


        }
        {
        System.out.println("Invoking storeStock...");
        int _storeStock_arg0 = 33;
        java.lang.String _storeStock__return = port.storeStock(_storeStock_arg0);
        System.out.println("storeStock.result=" + _storeStock__return);


        }

        System.exit(0);
    }

}
