
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package custodian;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-17T22:31:35.160+01:00
 * Generated source version: 3.5.1
 *
 */

@javax.jws.WebService(
                      serviceName = "CustodianImplService",
                      portName = "CustodianImplPort",
                      targetNamespace = "http://custodian/",
                      wsdlLocation = "http://localhost:8000/Custodian?WSDL",
                      endpointInterface = "custodian.Custodian")

public class CustodianImplPortImpl implements Custodian {

    private static final Logger LOG = Logger.getLogger(CustodianImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see custodian.Custodian#removeStock(int arg0)*
     */
    public java.lang.String removeStock(int arg0) {
        LOG.info("Executing operation removeStock");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return1986708917";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see custodian.Custodian#storeStock(int arg0)*
     */
    public java.lang.String storeStock(int arg0) {
        LOG.info("Executing operation storeStock");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return698370202";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
