package custodian;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-17T22:31:35.167+01:00
 * Generated source version: 3.5.1
 *
 */
@WebService(targetNamespace = "http://custodian/", name = "Custodian")
@XmlSeeAlso({ObjectFactory.class})
public interface Custodian {

    @WebMethod(operationName = "RemoveStock")
    @Action(input = "http://custodian/Custodian/RemoveStockRequest", output = "http://custodian/Custodian/RemoveStockResponse")
    @RequestWrapper(localName = "RemoveStock", targetNamespace = "http://custodian/", className = "custodian.RemoveStock")
    @ResponseWrapper(localName = "RemoveStockResponse", targetNamespace = "http://custodian/", className = "custodian.RemoveStockResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String removeStock(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod(operationName = "StoreStock")
    @Action(input = "http://custodian/Custodian/StoreStockRequest", output = "http://custodian/Custodian/StoreStockResponse")
    @RequestWrapper(localName = "StoreStock", targetNamespace = "http://custodian/", className = "custodian.StoreStock")
    @ResponseWrapper(localName = "StoreStockResponse", targetNamespace = "http://custodian/", className = "custodian.StoreStockResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String storeStock(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
